# Generated by Django 4.1.3 on 2022-12-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="소셜유저", max_length=20),
        ),
    ]
